---
- name:  0 print boxname and IP
  debug:
    msg: 'Starting to run playbook in {{ cookiecutter.box_name }} at {{ cookiecutter.box_ip }}'
    
- name: 1 Install aptitude
  package:
    name: aptitude
    state: present

- name: 2 Update and upgrade apt packages
  apt:
    upgrade: 'True'
    update_cache: 'True'
    cache_valid_time: 86400 #One day

- name: 3 Install apt packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-pip
    - python3-setuptools
    - zip
    - wget
    - git
    - vim
    - nginx
    - nginx-extras
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - tmux
    - lynx

- name: 4 which pip3 executable
  command: which pip3
  register: pip3_path
